export const LIST_PLACES = 'LIST_PLACES';
export const LIST_ORDERTYPES = 'LIST_ORDERTYPES';
export const LIST_FUNCTIONALITY_MODULES = 'LIST_FUNCTIONALITY_MODULES';
export const GET_PLACES_SMS = 'GET_PLACES_SMS';
export const GET_CITIES = 'GET_CITIES';